fix: need to subtract then multiply
```python-traceback
Traceback (most recent call last):
  File "/home/chia/.local/bin/plotman", line 33, in <module>
    sys.exit(load_entry_point('plotman', 'console_scripts', 'plotman')())
  File "/farm/plotman/src/plotman/plotman.py", line 179, in main
    interactive.run_interactive()
  File "/farm/plotman/src/plotman/interactive.py", line 335, in run_interactive
    curses.wrapper(curses_main)
  File "/home/chia/.pyenv/versions/3.9.2/lib/python3.9/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/farm/plotman/src/plotman/interactive.py", line 262, in curses_main
    jobs_win.addstr(0, 0, reporting.status_report(jobs, n_cols, jobs_h,
  File "/farm/plotman/src/plotman/reporting.py", line 95, in status_report
    row = ['...'] + ([''] * len(headings) - 1)
TypeError: unsupported operand type(s) for -: 'list' and 'int'
```