fix: skip missing files in plot_util.list_k32_plots()
Perhaps it would be good to use os.scandir() but this is the direct quick fix.  Presumably this plot was removed by rsync between listing the directory and checking its size.

```
Traceback (most recent call last):
  File "/home/chia/.local/bin/plotman", line 33, in <module>
    sys.exit(load_entry_point('plotman', 'console_scripts', 'plotman')())
  File "/farm/plotman/src/plotman/plotman.py", line 171, in main
    interactive.run_interactive()
  File "/farm/plotman/src/plotman/interactive.py", line 352, in run_interactive
    curses.wrapper(curses_main)
  File "/home/chia/.pyenv/versions/3.9.2/lib/python3.9/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/farm/plotman/src/plotman/interactive.py", line 187, in curses_main
    dst_report = reporting.dst_dir_report(
  File "/farm/plotman/src/plotman/reporting.py", line 160, in dst_dir_report
    dir_plots = plot_util.list_k32_plots(d)
  File "/farm/plotman/src/plotman/plot_util.py", line 54, in list_k32_plots
    if os.stat(plot).st_size > (0.95 * get_k32_plotsize()):
FileNotFoundError: [Errno 2] No such file or directory: '/farm/yards/900/plot-k32-2021-04-25-17-50-527165ae8b5ddc95cf5853fec7dfaaf6672246b3eec369458f84e28992b1602a.plot'
```